### ISSUE TITLE
quick start?

### ISSUE THREAD

**Issue by aladdin-add** [jaydenseric/ruck#3]
Hi, I'm extremely interested in ruck, but is there a quick way to get started (without copy these code from the README)?

**Comment by jaydenseric** [comment]
Glad to hear that, welcome :)

If you just want to quickly have a Ruck project running on your local machine to play around with, the fastest way is to clone one of the Ruck projects listed in the readme [“Examples”](https://github.com/jaydenseric/ruck#examples) section, and follow the (brief, don't worry) installation instructions in the specific project readme.

If you want to actually start a real Ruck project from scratch, I recommend following the Ruck readme [“Installation”](https://github.com/jaydenseric/ruck#installation) instructions step by step to create the required files. This way you will understand the purpose of each file, and how Ruck works as a system. It's actually simpler than all the writing may seem at first, because each file is explained in quite a bit of depth.

Ruck has a bit of a different philosophy to some other web app frameworks; there is not supposed to be any mysterious boilerplate a quick start script sets up on your behalf or black box magic about how any of it works. It's realistic for someone who is curious to be able to read the Ruck source code and learn how everything works, although that is not necessary to make apps.

If you have any further questions feel free to keep commenting here!

**Comment by aladdin-add** [comment]
just cloned ruck-website, and created a `./env.sh` as stated in readme, but got the following error 😂:
```bash
➜  ruck-website git:(main) ./scripts/dev.sh
Missing environment variable `ACCESS_TOKEN_GITHUB`.
```

I'll just try from scratch, and (maybe) make a github template later. :)

**Comment by jaydenseric** [comment]
You should be able to just set `ACCESS_TOKEN_GITHUB=""` in the `scripts/.env.sh` file and I think the only consequence will be loading errors if you visit routes that query GitHub data.

The simplest one to try would be the SVG symbol viewer app, as it doesn't have any dynamic routes or require env var tokens:

https://github.com/jaydenseric/svg-symbol-viewer#installation

The other side of the coin of the example being simple, is that you won't learn as much about how to do realistic things like query external APIs.

**Comment by aladdin-add** [comment]
I've finally made an app starter: https://github.com/weiran-zsd/ruck-starter.  🎉

just a few feedback:
* docs improvement. some components were imported, but not defined, e.g. `public/components/{Heading,Para}.mjs`
* importMap. it's quite awful to write the 4 `importMap.json` - esp. most of them are the same.
* I do like the buildless way, but, without the jsx, the DX is 🤪 . I think most react devs just won't write so many `h()`. :)
